name: Deploy node application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: create .env File
        run: |
          echo "PORT = 5000" >> config/config.env
          echo "NODE_ENV = production" >> config/config.env
          echo "DB_URL = mongodb+srv://${{secrets.MONGODB_USERNAME}}:${{secrets.MONGODB_PASSWORD}}@cambridgeapp.9ksvjfl.mongodb.net/cambridgeApp?retryWrites=true&w=majority&appName=CambridgeApp" >> config/config.env
      - name: Login to Docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: build docker image
        run: docker build -t kirankumaravel/cambridgeappbackend .
      - name: publish this image to docker hub
        run: docker push kirankumaravel/cambridgeappbackend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull kirankumaravel/cambridgeappbackend:latest
      - name: Remove existing docker container if already exists.
        shell: /usr/bin/bash -e {0}
        run: |
          CONTAINER_NAME="cambridgeappbackendcontainer"
          RUNNING_CONTAINER=$(docker ps -aq --filter "name=$CONTAINER_NAME")
          RUNNING_CONTAINER="${RUNNING_CONTAINER//[[:space:]]//}"
          echo "Container RC '$RUNNING_CONTAINER'"
          if [ -n "$RUNNING_CONTAINER" ]; then
            echo "Container is runnning, stopping and removing"
            docker stop $CONTAINER_NAME
            docker rm $CONTAINER_NAME
          fi
      - name: Remove the docker image to free space
        run: docker rmi kirankumaravel/cambridgeappbackend
      - name: Remove All Unused Images
        run: docker image prune -a -f
      - name: Run docker container
        run: docker run -d -p 5050:5000 --name cambridgeappbackendcontainer --rm kirankumaravel/cambridgeappbackend
